+incdir+./
+incdir+../rtl
../rtl/refresher_pos_8.v
../rtl/ahb.sv
../rtl/axi2native.v
../rtl/bankmachine_0.v
../rtl/bankmachine_1.v
../rtl/bankmachine_2.v
../rtl/bankmachine_3.v
../rtl/bankmachine_4.v
../rtl/bankmachine_5.v
../rtl/bankmachine_6.v
../rtl/bankmachine_7.v
../rtl/crossbar_2ports.v
../rtl/DFIAdapter.v
../rtl/mc_core.sv
../rtl/mc_top.sv
../rtl/multiplexer_b8.v
../rtl/wb2native.v
./tb_top.sv